# Fly.io deployment configuration
app = "campusconnect-monitor"
primary_region = "bom"  # Mumbai region for better latency to India

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"

[env]
  PORT = "8000"
  SERVICE_NAME = "Campus Connect Backend"
  BASE_URL = "https://campusconnect-v2.onrender.com"