# Railway deployment configuration
version: 2

build:
  commands:
    - pip install -r requirements.txt

start:
  cmd: python main.py

environment:
  - SERVICE_NAME=Campus Connect Backend
  - BASE_URL=https://campusconnect-v2.onrender.com
  - PORT=8000

healthcheck:
  path: /health
  interval: 30s
  timeout: 10s
  retries: 3